### PR TITLE
Fix type panic caused by some compare paths are deeper than overrides, but not supported by GetFromTreePath()

### LINKED ISSUE #18683: Upgrade panic when comparing values with overrides
This is caused by some compare paths are deeper than overrides, but not supported by GetFromTreePath()

The error and CLI command:

```
taohe@taohe:~/istio.io/operator$ istioctl140b2 x upgrade --wait --skip-confirmation --force --dry-run --logtostderr -f /usr/local/google/home/taohe/default.yaml

2019-11-06T04:17:50.142989Z	info	Client - istioctl version: 1.4.0

2019-11-06T04:17:50.170244Z	info	ReadProfileYAML for profile name: [Empty]
2019-11-06T04:17:50.170271Z	info	Loading values from compiled in VFS at path profiles/default.yaml
2019-11-06T04:17:50.320401Z	info	ReadProfileYAML for profile name: [Empty]
2019-11-06T04:17:50.320431Z	info	Loading values from compiled in VFS at path profiles/default.yaml
2019-11-06T04:17:50.397257Z	info	Warning. The target version 1.4-dev does not equal to the binary version 1.4.0
2019-11-06T04:17:50.397288Z	info	Upgrade - target version: 1.4-dev

2019-11-06T04:17:50.883310Z	info	Control Plane - citadel pod - istio-citadel-6c4ccc79bc-ghpbb - version: 1.4.0-beta.2
2019-11-06T04:17:50.883344Z	info	Control Plane - galley pod - istio-galley-5fb696ff98-m5dxv - version: 1.4.0-beta.2
2019-11-06T04:17:50.883354Z	info	Control Plane - ingressgateway pod - istio-ingressgateway-5477d4d87f-j7z8f - version: 1.4.0-beta.2
2019-11-06T04:17:50.883362Z	info	Control Plane - pilot pod - istio-pilot-568d4bbf9c-kwb4s - version: 1.4.0-beta.2
2019-11-06T04:17:50.883370Z	info	Control Plane - policy pod - istio-policy-79cc59bd9-64fhx - version: 1.4.0-beta.2
2019-11-06T04:17:50.883378Z	info	Control Plane - sidecar-injector pod - istio-sidecar-injector-5f65dc5999-9fj7r - version: 1.4.0-beta.2
2019-11-06T04:17:50.883394Z	info	Control Plane - telemetry pod - istio-telemetry-bd95dc7b8-5jwts - version: 1.4.0-beta.2
2019-11-06T04:17:50.883402Z	info	
2019-11-06T04:17:51.317075Z	info	Upgrade version check passed: 1.4.0-beta.2 -> 1.4-dev.

panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
istio.io/operator/pkg/name.GetFromTreePath(0xc000e58900, 0xc000eec8a0, 0x2, 0x2, 0xc000e5ca98, 0x1, 0xcd0000c0009ced36, 0xc0006e0680, 0x3)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/name/name.go:235 +0x4bd
istio.io/operator/pkg/name.GetFromTreePath(0xc000e58720, 0xc000eec890, 0x3, 0x3, 0xc000e5d5e8, 0x1, 0xc0009ced27, 0xc000eec880, 0xc000df0a70)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/name/name.go:232 +0x361
istio.io/operator/pkg/name.GetFromTreePath(0xc000ab74a0, 0xc000eec880, 0x4, 0x4, 0x4, 0x4, 0x217eac0, 0xc000c1ee20, 0xc000e747c0)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/name/name.go:232 +0x361
istio.io/operator/pkg/compare.genYamlIgnoreOpt.func1(0xc000df0a00, 0x8, 0x10, 0xc000e74800)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/compare/compare.go:184 +0x7b
github.com/google/go-cmp/cmp.pathFilter.filter(0xc000e4d220, 0x2a1d860, 0x410e7e0, 0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c3fc80, 0x194, 0x0, ...)
	github.com/google/go-cmp@v0.3.1/cmp/options.go:133 +0x4d
github.com/google/go-cmp/cmp.Options.filter(0xc000e08480, 0x3, 0x4, 0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c3fc80, 0x194, 0x0, ...)
	github.com/google/go-cmp@v0.3.1/cmp/options.go:68 +0x27c
github.com/google/go-cmp/cmp.(*state).tryOptions(0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c3fc80, 0x194, 0x0, 0x0, 0x0, 0x3)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:268 +0xb5
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88240, 0xc000ee9630)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:224 +0x296
github.com/google/go-cmp/cmp.(*state).statelessCompare(0xc00067ad80, 0x2a88240, 0xc000ee9630, 0x1, 0xc00067ad80)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:203 +0x97
github.com/google/go-cmp/cmp.(*state).compareSlice(0xc00067ad80, 0x2ae8f00, 0x211f980, 0x211f980, 0xc000895620, 0x97, 0x211f980, 0xc000905680, 0x97)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:421 +0x2be
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88300, 0xc000eec780)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:254 +0xad5
github.com/google/go-cmp/cmp.(*state).compareInterface(0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c1ee90, 0x94, 0x21ff240, 0xc000c1eea0, 0x94)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:526 +0x47b
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88200, 0xc000ae2300)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:260 +0xdd2
github.com/google/go-cmp/cmp.(*state).compareMap(0xc00067ad80, 0x2ae8f00, 0x220b300, 0x220b300, 0xc000855ef0, 0x15, 0x220b300, 0xc000ab67e0, 0x15)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:500 +0x3db
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88300, 0xc000eec640)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:256 +0xe4d
github.com/google/go-cmp/cmp.(*state).compareInterface(0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c1edb0, 0x94, 0x21ff240, 0xc000c1edc0, 0x94)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:526 +0x47b
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88200, 0xc000a1b2c0)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:260 +0xdd2
github.com/google/go-cmp/cmp.(*state).compareMap(0xc00067ad80, 0x2ae8f00, 0x220b300, 0x220b300, 0xc000855d10, 0x15, 0x220b300, 0xc000ab6570, 0x15)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:500 +0x3db
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88300, 0xc000b60b40)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:256 +0xe4d
github.com/google/go-cmp/cmp.(*state).compareInterface(0xc00067ad80, 0x2ae8f00, 0x21ff240, 0x21ff240, 0xc000c31950, 0x94, 0x21ff240, 0xc000c31960, 0x94)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:526 +0x47b
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a88200, 0xc000e4bb60)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:260 +0xdd2
github.com/google/go-cmp/cmp.(*state).compareMap(0xc00067ad80, 0x2ae8f00, 0x220b300, 0x220b300, 0xc0008362a0, 0x15, 0x220b300, 0xc0008362d0, 0x15)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:500 +0x3db
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00067ad80, 0x2a6e780, 0xc000e084c0)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:256 +0xe4d
github.com/google/go-cmp/cmp.Equal(0x220b300, 0xc0008362a0, 0x220b300, 0xc0008362d0, 0xc000e59470, 0x3, 0x3, 0x0)
	github.com/google/go-cmp@v0.3.1/cmp/compare.go:107 +0x3a0
istio.io/operator/pkg/compare.YAMLCmpWithIgnore(0xc0006c0a80, 0x2a31, 0xc0006be000, 0x2a08, 0x0, 0x0, 0x0, 0xc000f03500, 0x28ab, 0x0, ...)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/compare/compare.go:134 +0x4b7
istio.io/operator/cmd/mesh.checkUpgradeValues(0xc0006c0a80, 0x2a31, 0xc0006be000, 0x2a08, 0xc000f03500, 0x28ab, 0xc000e75d48)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/cmd/mesh/upgrade.go:238 +0x81
istio.io/operator/cmd/mesh.upgrade(0xc0008a0acc, 0xc000aec7d0, 0xc000e75d48, 0x2a1a960, 0xc0000dc010)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/cmd/mesh/upgrade.go:184 +0x896
istio.io/operator/cmd/mesh.UpgradeCmd.func1(0xc000768c80, 0xc000362cb0, 0x0, 0x7, 0x0, 0x0)
	istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/cmd/mesh/upgrade.go:105 +0x125
github.com/spf13/cobra.(*Command).execute(0xc000768c80, 0xc000362c40, 0x7, 0x7, 0xc000768c80, 0xc000362c40)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000acb680, 0x9, 0x9, 0xc000acb680)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	istio.io/istio@/istioctl/cmd/istioctl/main.go:29 +0x76
```

### PR DESCRIPTION
**Pull request by elfinhe**
Fix: https://github.com/istio/istio/issues/18683

### CODE REVIEW

File: pkg/name/name.go [hunk 1]
```diff
@@ -228,16 +228,21 @@ func GetFromTreePath(inputTree map[string]interface{}, path util.Path) (interfac
...
 	case []interface{}:
 		for _, node := range newRoot {
-			nextVal, found, err := GetFromTreePath(node.(map[string]interface{}), path[1:])
-			if err != nil {
-				continue
-			}
-			if found {
-				return nextVal, true, nil
+			switch nt := node.(type) {
+			case map[string]interface{}:
```
Comment (ostromart) [inline pkg/name/name.go]: This is probably ok for now, but the right fix is for this function to take an interface{} - then it should handle a slice, map or scalar separately. In fact I think there's already such a version floating around... 
But since there's not much time, feel free to leave a TODO or create an issue.

Comment (elfinhe) [reply pkg/name/name.go]: Fixed

File: pkg/name/name_test.go [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+		args    args
+		want    interface{}
+		found   bool
+		wantErr bool
+	}{
+		{
+			name: "found string node",
+			args: args{
+				inputTree: map[string]interface{}{
+					"k1": "v1",
```
Comment (ostromart) [inline pkg/name/name_test.go]: These test inputs are a bit small - it would be better to have a greater depth and more keys. One way to do this easily is to make inputTree a yaml string (then you can easily do maps and lists) and yaml.unmarshal it when you run the test.

**Review by ostromart — APPROVED** [review]
