### PR TITLE
fix invalid version format from docker build info.

### LINKED ISSUE #19753: [Operator] operator crash due to version panic
**Bug description**

The operator for the latest master failed to work because of version panic:
```
# out/linux_amd64/mesh manifest generate
panic: Malformed version: a3703b76cf4745f3d56bf653ed751509be116351-dirty

goroutine 1 [running]:
istio.io/operator/version.init.0()
	istio.io/operator@/version/version.go:46 +0x199
```

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/19753

The version from the docker build info is not valid Semantic Version, that will cause version unmarshal panic.

### CODE REVIEW

**Comment by howardjohn** [comment]
why is it set to a Sha? where did you download from?

File: version/version.go [hunk 1]
```diff
@@ -36,11 +35,6 @@ var (
 func init() {
 	var err error
 	operatorVer := OperatorVersionString
-	// If dockerinfo has a tag (e.g., specified by LDFlags), we will use it as the version of operator
-	tag := buildversion.DockerInfo.Tag
-	if tag != "" && tag != "unknown" {
```
Comment (elfinhe) [inline version/version.go]: instead we can just check version format here for those dev images: 
```
	if tag != "" && buildversion.IsVersionString(tag) {
```

Comment (howardjohn) [reply version/version.go]: we should never get a SHA anyways afaik, how is this built?

Comment (howardjohn) [reply version/version.go]: nevermind, I see how it can happen

**Comment by elfinhe** [comment]
This issue is also fixed in https://github.com/istio/operator/pull/710.

**Review by elfinhe — APPROVED** [review]
